name: build-and-publish
on:
  push:
    tags:
      - v*.*.*
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container:
      # image: "registry.gitlab.com/team-supercharge/oasg:13.0.1"
      image: node:18.15.0
      env:
        MAVEN_REPO_USERNAME: ${{ github.actor }}
        MAVEN_REPO_PASSWORD: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - run: apt update
      - run: apt install -y wget jq
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - run: npm ci
      - run: npx patch-package
      - run: npx oasg generate oasg-github-demo
      - run: npx oasg publish oasg-github-demo
